"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.program = void 0;
var commander_1 = require("commander");
var banner_1 = require("./banner");
var changes_1 = require("./changes");
var database_1 = require("./database");
var entity_1 = require("./entity");
var migration_1 = require("./migration");
var types_1 = require("./types");
var config = require('../../package.json');
var createProgram = function () {
    var program = new commander_1.Command();
    program.version(config.version, '-v, --version', 'Output the current version');
    (0, database_1.createDatabaseProgram)(program);
    (0, database_1.createDatabasePullProgram)(program);
    (0, banner_1.createBannerProgram)(program);
    (0, changes_1.createChangesProgram)(program);
    (0, entity_1.createEntityProgram)(program);
    (0, migration_1.createMigrationProgram)(program);
    (0, types_1.generateEntityTypes)(program);
    return program;
};
exports.program = createProgram();
